-- Write SQL query to solve the problem given below 
-- Consider a database containing two tables named as Customer and Salesman 
-- For this you need to create a Customer table 
-- In Customer table attributes are customer id, customer name, city, grade and 
-- salesman id

-- table CUSTOMER_K
CREATE TABLE CUSTOMER_K(
CUSTOMER_ID INT PRIMARY KEY,
CUST_NAME VARCHAR(50) NOT NULL,
CITY VARCHAR(25) NOT NULL,
GRADE INT NULL,
SALESMAN_ID INT NOT NULL,
FOREIGN KEY (SALESMAN_ID) references SALESMAN(SALESMAN_ID)
);

DROP TABLE CUSTOMER_K;

TRUNCATE TABLE CUSTOMER_K;

INSERT INTO CUSTOMER_K VALUES(3002,'NICK RIMANDO','NEW YORK',100,5001);
INSERT INTO CUSTOMER_K VALUES(3007,'BRAD DAVIS','NEW YORK',200,5001);
INSERT INTO CUSTOMER_K VALUES(3005,'GRAHAM ZUSI','CALIFORNIA',200,5002);
INSERT INTO CUSTOMER_K VALUES(3008,'JULIAN GREEN','LONDON',300,5002);
INSERT INTO CUSTOMER_K VALUES(3004,'FABIAN JOHNSON','PARIS',300,5006);
INSERT INTO CUSTOMER_K VALUES(3009,'GEOFF CAMERON','BERLIN',100,5003);
INSERT INTO CUSTOMER_K VALUES(3003,'JOZY ALTIDOR','MOSCOW',200,5007);
INSERT INTO CUSTOMER_K(CUSTOMER_ID,CUST_NAME,CITY,SALESMAN_ID) VALUES(3001,'BRAD GUZAN','LONDON',5005);

-- In Salesman table attributes will be salesman id, name, city and commission
-- TABLE SALESMAN
CREATE TABLE SALESMAN(
SALESMAN_ID INT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
CITY VARCHAR(15) NOT NULL,
COMMISSION FLOAT NOT NULL
);

DROP TABLE SALESMAN;

TRUNCATE TABLE SALESMAN;

INSERT INTO SALESMAN VALUES(5001,'JAMES HOOG','NEW YORK',0.15);
INSERT INTO SALESMAN VALUES(5002,'NAIL KNITE','PARIS',0.13);
INSERT INTO SALESMAN VALUES(5005,'PIT ALEX','LONDON',0.11);
INSERT INTO SALESMAN VALUES(5006,'MC LYON','PARIS',0.14);
INSERT INTO SALESMAN VALUES(5007,'PAUL ADAM','ROME',0.13);
INSERT INTO SALESMAN VALUES(5003,'LAUSON HEN','SAN JOSE',0.12);

SELECT * FROM CUSTOMER_K;

SELECT * FROM SALESMAN;

-- From the above given tables write a SQL query to find the salesperson(s) and the 
-- customer(s) represented here. Return the Customer Name, City, Salesman, 
-- commission.

SELECT CUSTOMER_K.CUST_NAME, SALESMAN.NAME, SALESMAN.CITY,SALESMAN.COMMISSION
FROM SALESMAN
RIGHT JOIN CUSTOMER_K ON SALESMAN.SALESMAN_ID = CUSTOMER_K.SALESMAN_ID;











